CREATE TABLE IF NOT EXISTS `tk_audio_export_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '音频导出任务编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `company_id` bigint DEFAULT NULL COMMENT '企业编号',
  `request_id` varchar(64) NOT NULL COMMENT '客户端幂等请求标识',
  `script_text` text NOT NULL COMMENT '配音文案',
  `tts_provider` varchar(32) NOT NULL COMMENT '配音提供方',
  `voice_code` varchar(255) DEFAULT NULL COMMENT 'DashScope 音色编码',
  `voice_profile_id` bigint DEFAULT NULL COMMENT '音色档案编号',
  `mimo_voice_mode` varchar(32) DEFAULT NULL COMMENT 'MiMo 音色模式',
  `mimo_voice_code` varchar(255) DEFAULT NULL COMMENT 'MiMo 预置音色编码',
  `mimo_voice_prompt` text DEFAULT NULL COMMENT 'MiMo 音色设计提示词',
  `mimo_voice_sample_url` varchar(1024) DEFAULT NULL COMMENT 'MiMo 音色克隆样本地址',
  `target_language` varchar(32) NOT NULL COMMENT '配音语言',
  `audio_url` varchar(1024) DEFAULT NULL COMMENT '生成音频地址',
  `status` varchar(32) NOT NULL COMMENT '状态：PROCESSING/SUCCESS/FAILED',
  `fail_reason` text DEFAULT NULL COMMENT '失败原因',
  `credit_log_id` bigint DEFAULT NULL COMMENT '积分流水编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tk_audio_export_task_request` (`tenant_id`, `request_id`, `deleted`),
  KEY `idx_tk_audio_export_task_status` (`tenant_id`, `status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TK 独立音频导出任务';
