CREATE TABLE IF NOT EXISTS `tk_open_video_transcript_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务编号',
  `source_url` varchar(2048) NOT NULL COMMENT '原始视频链接',
  `source_url_hash` varchar(64) NOT NULL COMMENT '原始链接 SHA-256',
  `target_language` varchar(32) DEFAULT NULL COMMENT '目标语言',
  `resolved_video_url` varchar(2048) DEFAULT NULL COMMENT '下载后视频链接',
  `cover_url` varchar(2048) DEFAULT NULL COMMENT '封面链接',
  `video_duration` int DEFAULT NULL COMMENT '视频时长秒',
  `resolution` varchar(64) DEFAULT NULL COMMENT '视频分辨率',
  `audio_url` varchar(2048) DEFAULT NULL COMMENT '提取音频链接',
  `audio_duration` decimal(10,2) DEFAULT NULL COMMENT '音频时长秒',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '失败原因',
  `transcript_text` longtext DEFAULT NULL COMMENT '完整口播文案',
  `segments_json` longtext DEFAULT NULL COMMENT '分段时间轴 JSON',
  `words_json` longtext DEFAULT NULL COMMENT '词级时间轴 JSON',
  `asr_provider` varchar(64) DEFAULT NULL COMMENT 'ASR 提供方',
  `asr_model` varchar(128) DEFAULT NULL COMMENT 'ASR 模型',
  `raw_asr_result` longtext DEFAULT NULL COMMENT 'ASR 原始结果',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_source_url_hash` (`source_url_hash`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TK Open 视频文案时间轴提取任务';
