-- Additive latest-statistics migration. Apply BEFORE tk.social.stats.enabled=true.
-- No publishing/account rows are modified. The bounded scheduler seeds existing SUCCESS details.

CREATE TABLE IF NOT EXISTS tk_social_account_stats (
  id bigint NOT NULL AUTO_INCREMENT,
  tenant_id bigint NOT NULL,
  company_id bigint NOT NULL,
  object_id bigint NOT NULL COMMENT 'bound account id',
  social_account_id bigint NOT NULL,
  platform varchar(32) NOT NULL,
  creator varchar(64) NOT NULL DEFAULT '',
  published_time datetime DEFAULT NULL,
  followers bigint DEFAULT NULL,
  following bigint DEFAULT NULL,
  media_count bigint DEFAULT NULL,
  views bigint DEFAULT NULL,
  likes bigint DEFAULT NULL,
  comments bigint DEFAULT NULL,
  shares bigint DEFAULT NULL,
  saves bigint DEFAULT NULL,
  reach bigint DEFAULT NULL,
  metrics_json mediumtext NOT NULL,
  sync_status varchar(32) NOT NULL DEFAULT 'PENDING',
  last_attempt_time datetime DEFAULT NULL,
  last_success_time datetime DEFAULT NULL,
  next_sync_time datetime DEFAULT NULL,
  last_manual_time datetime DEFAULT NULL,
  retry_count int NOT NULL DEFAULT 0,
  lease_token varchar(64) DEFAULT NULL,
  lease_until datetime DEFAULT NULL,
  error_code varchar(128) DEFAULT NULL,
  error_message varchar(512) DEFAULT NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_social_account_stats_object (tenant_id, object_id),
  KEY idx_social_account_stats_due (next_sync_time, lease_until),
  KEY idx_social_account_stats_lease (lease_until),
  KEY idx_social_account_stats_scope (tenant_id, company_id, social_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS tk_social_media_stats (
  id bigint NOT NULL AUTO_INCREMENT,
  tenant_id bigint NOT NULL,
  company_id bigint NOT NULL,
  object_id bigint NOT NULL COMMENT 'SUCCESS publish detail id',
  social_account_id bigint NOT NULL,
  platform varchar(32) NOT NULL,
  creator varchar(64) NOT NULL DEFAULT '',
  published_time datetime DEFAULT NULL,
  followers bigint DEFAULT NULL,
  following bigint DEFAULT NULL,
  media_count bigint DEFAULT NULL,
  views bigint DEFAULT NULL,
  likes bigint DEFAULT NULL,
  comments bigint DEFAULT NULL,
  shares bigint DEFAULT NULL,
  saves bigint DEFAULT NULL,
  reach bigint DEFAULT NULL,
  metrics_json mediumtext NOT NULL,
  sync_status varchar(32) NOT NULL DEFAULT 'PENDING',
  last_attempt_time datetime DEFAULT NULL,
  last_success_time datetime DEFAULT NULL,
  next_sync_time datetime DEFAULT NULL,
  last_manual_time datetime DEFAULT NULL,
  retry_count int NOT NULL DEFAULT 0,
  lease_token varchar(64) DEFAULT NULL,
  lease_until datetime DEFAULT NULL,
  error_code varchar(128) DEFAULT NULL,
  error_message varchar(512) DEFAULT NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_social_media_stats_object (tenant_id, object_id),
  KEY idx_social_media_stats_due (next_sync_time, lease_until),
  KEY idx_social_media_stats_lease (lease_until),
  KEY idx_social_media_stats_scope (tenant_id, company_id, social_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
