-- Additive latest-statistics migration. Apply BEFORE tk.social.stats.enabled=true.
-- No publishing/account rows are modified. The bounded scheduler seeds existing SUCCESS details.

CREATE TABLE IF NOT EXISTS tk_social_account_stats (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  tenant_id bigint NOT NULL COMMENT '租户编号',
  company_id bigint NOT NULL COMMENT '公司编号',
  object_id bigint NOT NULL COMMENT '绑定账号编号',
  social_account_id bigint NOT NULL COMMENT '社交账号编号',
  platform varchar(32) NOT NULL COMMENT '社交平台',
  creator varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  published_time datetime DEFAULT NULL COMMENT '发布时间',
  followers bigint DEFAULT NULL COMMENT '粉丝数',
  following bigint DEFAULT NULL COMMENT '关注数',
  media_count bigint DEFAULT NULL COMMENT '媒体数量',
  views bigint DEFAULT NULL COMMENT '播放量',
  likes bigint DEFAULT NULL COMMENT '点赞数',
  comments bigint DEFAULT NULL COMMENT '评论数',
  shares bigint DEFAULT NULL COMMENT '分享数',
  saves bigint DEFAULT NULL COMMENT '收藏数',
  reach bigint DEFAULT NULL COMMENT '触达人数',
  metrics_json mediumtext NOT NULL COMMENT '统计指标 JSON',
  sync_status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '同步状态',
  last_attempt_time datetime DEFAULT NULL COMMENT '最近尝试时间',
  last_success_time datetime DEFAULT NULL COMMENT '最近成功时间',
  next_sync_time datetime DEFAULT NULL COMMENT '下次同步时间',
  last_manual_time datetime DEFAULT NULL COMMENT '最近手动同步时间',
  retry_count int NOT NULL DEFAULT 0 COMMENT '重试次数',
  lease_token varchar(64) DEFAULT NULL COMMENT '租约令牌',
  lease_until datetime DEFAULT NULL COMMENT '租约截止时间',
  error_code varchar(128) DEFAULT NULL COMMENT '错误码',
  error_message varchar(512) DEFAULT NULL COMMENT '错误信息',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_social_account_stats_object (tenant_id, object_id),
  KEY idx_social_account_stats_due (next_sync_time, lease_until),
  KEY idx_social_account_stats_lease (lease_until),
  KEY idx_social_account_stats_scope (tenant_id, company_id, social_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='TK 社交账号统计';

CREATE TABLE IF NOT EXISTS tk_social_media_stats (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  tenant_id bigint NOT NULL COMMENT '租户编号',
  company_id bigint NOT NULL COMMENT '公司编号',
  object_id bigint NOT NULL COMMENT '成功发布明细编号',
  social_account_id bigint NOT NULL COMMENT '社交账号编号',
  platform varchar(32) NOT NULL COMMENT '社交平台',
  creator varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  published_time datetime DEFAULT NULL COMMENT '发布时间',
  followers bigint DEFAULT NULL COMMENT '粉丝数',
  following bigint DEFAULT NULL COMMENT '关注数',
  media_count bigint DEFAULT NULL COMMENT '媒体数量',
  views bigint DEFAULT NULL COMMENT '播放量',
  likes bigint DEFAULT NULL COMMENT '点赞数',
  comments bigint DEFAULT NULL COMMENT '评论数',
  shares bigint DEFAULT NULL COMMENT '分享数',
  saves bigint DEFAULT NULL COMMENT '收藏数',
  reach bigint DEFAULT NULL COMMENT '触达人数',
  metrics_json mediumtext NOT NULL COMMENT '统计指标 JSON',
  sync_status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '同步状态',
  last_attempt_time datetime DEFAULT NULL COMMENT '最近尝试时间',
  last_success_time datetime DEFAULT NULL COMMENT '最近成功时间',
  next_sync_time datetime DEFAULT NULL COMMENT '下次同步时间',
  last_manual_time datetime DEFAULT NULL COMMENT '最近手动同步时间',
  retry_count int NOT NULL DEFAULT 0 COMMENT '重试次数',
  lease_token varchar(64) DEFAULT NULL COMMENT '租约令牌',
  lease_until datetime DEFAULT NULL COMMENT '租约截止时间',
  error_code varchar(128) DEFAULT NULL COMMENT '错误码',
  error_message varchar(512) DEFAULT NULL COMMENT '错误信息',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_social_media_stats_object (tenant_id, object_id),
  KEY idx_social_media_stats_due (next_sync_time, lease_until),
  KEY idx_social_media_stats_lease (lease_until),
  KEY idx_social_media_stats_scope (tenant_id, company_id, social_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='TK 社交媒体统计';
