-- Additive migration. Does not rewrite old outcomes or callback history.
CREATE TABLE IF NOT EXISTS tk_open_tiktok_publish_attempt (
  id bigint NOT NULL AUTO_INCREMENT,
  client_id varchar(64) NOT NULL,
  task_id varchar(64) NOT NULL,
  detail_id varchar(64) NOT NULL,
  attempt_no int NOT NULL DEFAULT 0,
  owner_token varchar(64) DEFAULT NULL,
  phase varchar(40) NOT NULL,
  started_time datetime NOT NULL,
  heartbeat_time datetime NOT NULL,
  publish_id varchar(256) DEFAULT NULL,
  upload_source varchar(32) DEFAULT NULL,
  upload_url_cipher text,
  file_sha256 varchar(64) DEFAULT NULL,
  file_size bigint DEFAULT NULL,
  last_error varchar(1000) DEFAULT NULL,
  terminal_source varchar(40) DEFAULT NULL,
  terminal_time datetime DEFAULT NULL,
  next_reconcile_time datetime DEFAULT NULL,
  reconcile_count int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_detail_attempt (detail_id, attempt_no),
  KEY idx_publish_id (publish_id),
  KEY idx_reconcile (phase, next_reconcile_time),
  KEY idx_heartbeat (phase, heartbeat_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
