-- Additive migration. Does not rewrite old outcomes or callback history.
CREATE TABLE IF NOT EXISTS tk_open_tiktok_publish_attempt (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  client_id varchar(64) NOT NULL COMMENT '开放 API 客户端编号',
  task_id varchar(64) NOT NULL COMMENT '发布任务编号',
  detail_id varchar(64) NOT NULL COMMENT '发布明细编号',
  attempt_no int NOT NULL DEFAULT 0 COMMENT '尝试次数',
  owner_token varchar(64) DEFAULT NULL COMMENT '执行者令牌',
  phase varchar(40) NOT NULL COMMENT '发布阶段',
  started_time datetime NOT NULL COMMENT '开始时间',
  heartbeat_time datetime NOT NULL COMMENT '心跳时间',
  publish_id varchar(256) DEFAULT NULL COMMENT 'TikTok 发布编号',
  upload_source varchar(32) DEFAULT NULL COMMENT '上传来源',
  upload_url_cipher text COMMENT '上传地址密文',
  file_sha256 varchar(64) DEFAULT NULL COMMENT '文件 SHA-256',
  file_size bigint DEFAULT NULL COMMENT '文件大小（字节）',
  last_error varchar(1000) DEFAULT NULL COMMENT '最近错误信息',
  terminal_source varchar(40) DEFAULT NULL COMMENT '终态来源',
  terminal_time datetime DEFAULT NULL COMMENT '终态时间',
  next_reconcile_time datetime DEFAULT NULL COMMENT '下次对账时间',
  reconcile_count int NOT NULL DEFAULT 0 COMMENT '对账次数',
  creator varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updater varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_detail_attempt (detail_id, attempt_no),
  KEY idx_publish_id (publish_id),
  KEY idx_reconcile (phase, next_reconcile_time),
  KEY idx_heartbeat (phase, heartbeat_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TK 开放 API TikTok 发布尝试记录';
