/data/Tk/shared/logs/nginx-access.log
/data/Tk/shared/logs/nginx-error.log
/data/Tk/shared/logs/*.console.log
/data/Tk/current/logs/*.out
/data/Tk/current/logs/*.out.log
/data/Tk/current/logs/*.err
/data/Tk/current/logs/*.err.log {
    daily
    rotate 3
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    su linux linux
}
