import { tkEnglishTextMap } from '@/locales/tk'

const cjkPattern = /[\u3400-\u9fff]/
const phraseMap: Record<string, string> = {
  ...tkEnglishTextMap,
  // Normal Chinese text returned by menus or backend data.
  '素材库': 'Materials',
  '素材视频': 'Material Videos',
  '脚步提拉带': 'Foot Lift Strap',
  '秀美二楼': 'Xiumei 2F',
  '视频': 'Video',
  '请输入菜单内容': 'Please enter menu content',
  '首页': 'Home',
  '翻译内容': 'Translated Content',
  'TK翻译内容': 'TK Translated Content',
  '视频翻译内容': 'Video Translations',
  'AI翻译内容': 'AI Translations',
  '翻译内容视频': 'Translation Videos',
  '翻译视频': 'Translated Video',
  '视频发布中心': 'Video Publishing Center',
  '待发布视频': 'Videos to Publish',
  '账号矩阵': 'Account Matrix',
  '发布任务': 'Publishing Tasks',
  '发布明细': 'Publishing Details',
  '已授权账号': 'Authorized Accounts',
  '待发布任务': 'Pending Publishing Tasks',
  '失败任务': 'Failed Tasks',
  'Token异常': 'Token Issues',
  '任务标题': 'Task Title',
  '素材库ID': 'Library ID',
  '目标时长': 'Target Duration',
  '创建时间': 'Created Time',
  '操作': 'Actions',
  '搜索': 'Search',
  '重置': 'Reset',
  '刷新': 'Refresh',
  '官方授权': 'Official Authorization',
  '二维码授权': 'QR Code Authorization',
  '新建分组': 'New Group',
  '授权': 'Authorization',
  '已授权': 'Authorized',
  '未授权': 'Unauthorized',
  '默认隐私': 'Default Privacy',
  '默认开关': 'Default Switches',
  '标签': 'Tags',
  '失败原因': 'Failure Reason',
  '用户已解绑 TikTok 授权': 'The user has unbound TikTok authorization',
  '配置': 'Configure',
  '解绑': 'Unbind',
  '账号分组': 'Account Groups',
  '分组': 'Group',
  '账号数': 'Accounts',
  '备注': 'Remarks',
  '状态': 'Status',
  '编辑': 'Edit',
  '删除': 'Delete',
  '关键词': 'Keyword',
  '流水号': 'Trace ID',
  '标题': 'Title',
  '文案': 'Script',
  '名称': 'Name',
  '用户名': 'Username',
  '账号': 'Account',
  '管理员': 'Administrator',
  '有效': 'Valid',
  '异常': 'Invalid',
  '过期': 'Expired',
  '评论': 'Comments',
  '合拍': 'Duet',
  '拼接': 'Stitch',
  '启用': 'Enabled',
  '禁用': 'Disabled',
  '未设置场景': 'Scene not set',
  'AI分析记录': 'AI Analysis Records',
  '视频生成记录': 'Video Generation Records',
  '链接 / 产品 / 卖点': 'Link / Product / Selling Points',
  '请输入业务流水号': 'Please enter business trace ID',
  '请输入任务标题': 'Please enter task title',
  '分析对象': 'Analysis Target',
  'TikTok 对标链接': 'TikTok Reference Link',
  '流水号：': 'Trace ID:',
  '链路状态': 'Pipeline Status',
  '对标分析：': 'Reference Analysis:',
  '卖点提炼：': 'Selling Point Extraction:',
  '文案标题：': 'Script Titles:',
  '核心卖点': 'Core Selling Points',
  '默认文案标题': 'Default Script Title',
  '视频时长': 'Video Duration',
  '详情': 'Details',
  '回溯': 'Trace',
  '开头视频': 'Opening Video',
  '进度': 'Progress',
  '剪辑明细': 'Clip Details',
  '生成任务': 'Generation Task',
  '生成详情': 'Generation Details',
  '任务ID': 'Task ID',
  '业务流水号': 'Business Trace ID',
  '业务流水号已复制': 'Business trace ID copied',
  '复制': 'Copy',
  'TikTok 链接': 'TikTok Link',
  'AI文案': 'AI Script',
  '配音': 'Voiceover',
  '字幕': 'Subtitles',
  '当前步骤': 'Current Step',
  '剪辑结构': 'Clip Structure',
  '顺序': 'Order',
  '来源': 'Source',
  '用途': 'Use',
  '素材名称': 'Material Name',
  '素材ID': 'Material ID',
  '使用方式': 'Usage Mode',
  '素材时长': 'Material Duration',
  '抽取说明': 'Selection Note',
  '当前任务暂无输出文件': 'The current task has no output file yet',
  '视频已过期': 'Video expired',
  '生成视频': 'Generated Video',
  '已完成': 'Completed',
  '待生成': 'Waiting to Generate',
  '待执行': 'Waiting',
  '分析中': 'Analyzing',
  '成功': 'Success',
  '失败': 'Failed',
  '排队中': 'Queued',
  '分析文案': 'Analyzing Script',
  '文案就绪': 'Script Ready',
  '配音就绪': 'Voiceover Ready',
  '随机抽取素材中': 'Selecting Materials',
  '素材随机抽取': 'Materials Selected',
  '字幕时间轴就绪': 'Subtitle Timeline Ready',
  '画面分析就绪': 'Visual Analysis Ready',
  '剪辑方案就绪': 'Clip Plan Ready',
  '渲染中': 'Rendering',
  '导出中': 'Exporting',
  '个片段': ' clips',
  '合计': 'total',

  // Creative workshop.
  'AI 创意工坊': 'AI Creative Workshop',
  '把商品卖点变成可投放创意': 'Turn product selling points into launch-ready creatives',
  '输入产品信息、场景诉求或参考脚本，快速预生成短视频、图片、头像和带货创意方案。':
    'Enter product details, scene requirements, or reference scripts to quickly pre-generate short videos, images, avatars, and commerce creative plans.',
  '请输入创意需求。例如：为一款便携补光灯生成 TikTok 带货短视频，突出轻便、可调光、适合直播和旅行拍摄。禁止暴力、色情、侵权及名人相关内容。':
    'Enter a creative request. For example: generate a TikTok commerce short video for a portable fill light, highlighting portability, adjustable brightness, livestream use, and travel shooting. Avoid violent, sexual, infringing, or celebrity-related content.',
  '提示词助手': 'Prompt Assistant',
  '生成中': 'Generating',
  '生成创意': 'Generate Creative',
  'AI 视频': 'AI Video',
  'AI 图片': 'AI Image',
  '数字人': 'Digital Human',
  '创意脚本': 'Creative Script',
  '闪电创意引擎': 'Lightning Creative Engine',
  '推荐': 'Recommended',
  '商品短片生成': 'Product Short Video Generator',
  '限时体验': 'Limited Trial',
  '图像创意生成': 'Image Creative Generator',
  '数字人分身': 'Digital Human Avatar',
  '全部': 'All',
  'AI 视频生成': 'AI Video Generation',
  'AI 图片生成': 'AI Image Generation',
  '数字人头像': 'Digital Human Avatar',
  '全能闪电': 'All-in-One Lightning',
  '快速生成短视频创意': 'Quickly generate short video creatives',
  '种草短片 2.0': 'Product Seeding Shorts 2.0',
  '商品卖点自动成片': 'Turn product selling points into videos automatically',
  '爆款脚本视频': 'Viral Script Video',
  '脚本、镜头、字幕一体生成': 'Generate scripts, shots, and subtitles together',
  '限时 50% Off': 'Limited 50% Off',
  '智能配图': 'Smart Image Matching',
  '电商主图与场景图': 'E-commerce hero and lifestyle images',
  '商品海报': 'Product Poster',
  '促销图与广告素材': 'Promotion images and ad assets',
  'AI 精修图': 'AI Retouched Image',
  '画质增强与背景重绘': 'Quality enhancement and background redraw',
  '视频复刻': 'Video Remake',
  '参考结构生成新创意': 'Generate new creatives from a reference structure',
  'UGC 带货内容': 'UGC Commerce Content',
  '达人视角商品口播': 'Creator-style product talking points',
  '我的数字人': 'My Digital Human',
  '虚拟主播和品牌分身': 'Virtual hosts and brand avatars',
  '数字人长视频': 'Long-form Digital Human Video',
  '知识讲解与带货直播切片': 'Educational and commerce livestream clips',
  '真人 + 动作': 'Real Person + Motion',
  '动作参考驱动数字人': 'Drive digital humans from motion references',
  '提示词反推': 'Prompt Reverse Engineering',
  '从图片/视频生成提示词': 'Generate prompts from images/videos',
  '素材上传入口已预留，后续会接入文件素材库。':
    'Material upload has been reserved and will be connected to the file material library later.',
  '素材上传入口已预留，后续可接入图片/视频上传接口':
    'Material upload is reserved and can later connect to image/video upload APIs.',
  '为一款跨境电商商品生成 TikTok 创意短视频，要求：前 3 秒强钩子，中段展示核心卖点和使用场景，结尾加入购买引导；画面干净、节奏快、适合竖屏投放。':
    'Generate a TikTok creative short video for a cross-border e-commerce product: strong hook in the first 3 seconds, core selling points and usage scenarios in the middle, and a purchase call-to-action at the end. Keep visuals clean, fast-paced, and optimized for vertical placement.',
  '提示词助手接口已预留，后续会基于素材和商品信息生成提示词。':
    'The prompt assistant API has been reserved and will generate prompts from materials and product information later.',
  '提示词助手接口已预留，可在此接入 AI 改写能力':
    'The prompt assistant API is reserved and can connect to AI rewriting here.',
  '客服与使用帮助入口已预留。': 'The support and help entry has been reserved.',
  '客服与使用帮助入口已预留': 'The support and help entry has been reserved.',
  '请先输入创意需求': 'Please enter a creative request first',
  '创意生成任务已提交': 'Creative generation task submitted',
  '外部生成接口仍是占位状态，后续可接入第三方模型服务。':
    'The external generation API is still a placeholder and can later connect to third-party model services.',
  '外部生成接口仍是占位状态，请后续补充真实接口':
    'The external generation API is still a placeholder. Please connect the real API later.',

  // Company and business administration.
  '公司名称不能为空': 'Company name is required',
  '公司名称': 'Company Name',
  '请输入公司名称': 'Please enter company name',
  '新增公司': 'New Company',
  '编辑公司': 'Edit Company',
  '联系人': 'Contact',
  '联系电话': 'Contact Phone',
  '请输入联系人': 'Please enter contact',
  '请输入联系电话': 'Please enter contact phone',
  '更新成功': 'Updated successfully',
  '创建成功': 'Created successfully',
  '删除成功': 'Deleted successfully',
  '请选择状态': 'Please select status',
  '取消': 'Cancel',
  '确定': 'Confirm',
  '业务类型': 'Business Type',
  '请输入业务类型': 'Please enter business type',
  '业务ID': 'Business ID',
  '级别': 'Level',
  '请选择级别': 'Please select level',
  '信息': 'Info',
  '警告': 'Warning',
  '错误': 'Error',
  '处理中': 'Processing',
  '操作人': 'Operator',
  '业务': 'Business',
  '动作': 'Action',
  '消息': 'Message',

  // Current business data seen in production.
  '鑴氭鎻愭媺甯?': 'Foot Lift Strap',
  '榛勮壊鍒嗘寚鏉?': 'Yellow Finger Separator Board',
  '榛戣壊瓒充笅鍨傝冻鎵?': 'Black Foot Drop Brace',
  '甯﹁揣娣峰壀': 'Sales Remix',
  '绉€缇庝簩妤?': 'Xiumei 2F',
  '绉€缇庝竴妤?': 'Xiumei 1F',
  '绉€缇?': 'Xiumei',
  'ClipForge Studio': 'ClipForge Studio',
  'ClipForge Studio 01': 'ClipForge Studio 01',
  '娴嬭瘯涓€缁?': 'Test Group 1',
  '娴嬭瘯浜岀粍': 'Test Group 2',
  '娴嬭瘯涓夌粍': 'Test Group 3',

  // Layout and shared controls.
  '绯荤粺绠＄悊': 'System Management',
  '棣栭〉': 'Home',
  '绱犳潗搴?': 'Materials',
  '鐢熸垚璁板綍': 'Generation Records',
  '瑙嗛鍙戝竷涓績': 'Video Publishing',
  '鍒涙剰宸ュ潑': 'Creative Studio',
  'AI鍒涙剰宸ュ潑': 'AI Creative Studio',
  '鍏徃绠＄悊': 'Company Management',
  '涓氬姟鏃ュ織': 'Business Logs',
  '鐢ㄦ埛绠＄悊': 'User Management',
  '瑙掕壊绠＄悊': 'Role Management',
  '鑿滃崟绠＄悊': 'Menu Management',
  '閮ㄩ棬绠＄悊': 'Department Management',
  '绉熸埛绠＄悊': 'Tenant Management',
  '鏃ュ織绠＄悊': 'Log Management',
  '鐧诲綍鏃ュ織': 'Login Logs',
  '鎿嶄綔鏃ュ織': 'Operation Logs',
  '瀛楀吀绠＄悊': 'Dictionary Management',
  '閫氱煡鍏憡': 'Notices',
  '鑿滃崟鎼滅储': 'Menu Search',
  '璇疯緭鍏ヨ彍鍗曞唴瀹?': 'Please enter menu content',
  '鎴戠殑绔欏唴淇?': 'My Messages',
  '鏌ョ湅鍏ㄩ儴': 'View All',

  // Common table and form copy.
  '鎼滅储': 'Search',
  '閲嶇疆': 'Reset',
  '鏂板': 'Create',
  '鍒涘缓': 'Create',
  '鏂板缓': 'Create',
  '瀵煎叆': 'Import',
  '瀵煎嚭': 'Export',
  '鎵归噺鍒犻櫎': 'Batch Delete',
  '淇敼': 'Edit',
  '缂栬緫': 'Edit',
  '鏇村': 'More',
  '鍒犻櫎': 'Delete',
  '鍙栨秷': 'Cancel',
  '纭畾': 'Confirm',
  '淇濆瓨': 'Save',
  '鍏抽棴': 'Close',
  '鍒锋柊': 'Refresh',
  '鏌ョ湅': 'View',
  '棰勮': 'Preview',
  '涓嬭浇': 'Download',
  '澶嶅埗': 'Copy',
  '鍚屾': 'Sync',
  '閲嶈瘯': 'Retry',
  '鏄庣粏': 'Details',
  '閰嶇疆': 'Configure',
  '鐘舵€?': 'Status',
  '鎿嶄綔': 'Actions',
  '鍒涘缓鏃堕棿': 'Created Time',
  '鏇存柊鏃堕棿': 'Updated Time',
  '寮€濮嬫棩鏈?': 'Start date',
  '缁撴潫鏃ユ湡': 'End date',
  '鍏抽敭璇?': 'Keyword',
  '娴佹按鍙?': 'Trace ID',
  '涓氬姟娴佹按鍙?': 'Business Trace ID',
  '璇疯緭鍏ヤ笟鍔℃祦姘村彿': 'Please enter business trace ID',
  '璇烽€夋嫨鐘舵€?': 'Please select status',
  '璇疯緭鍏?': 'Please enter',
  '璇烽€夋嫨': 'Please select',
  '鍚敤': 'Enabled',
  '寮€鍚?': 'Enabled',
  '姝ｅ父': 'Enabled',
  '绂佺敤': 'Disabled',
  '鍋滅敤': 'Disabled',
  '鍏抽棴鐘舵€?': 'Disabled',
  '鎴愬姛': 'Success',
  '澶辫触': 'Failed',
  '澶勭悊涓?': 'Processing',
  '鎺掗槦涓?': 'Queued',
  '寰呮墽琛?': 'Waiting',
  '宸插畬鎴?': 'Completed',
  '鏆傛棤鏁版嵁': 'No data',
  '鏆傛棤鎻忚堪': 'No description',
  '鎬昏': 'Total',
  '鍏?': 'Total',
  '鏉?': 'items',
  '椤?': 'page',

  // Material library.
  '绱犳潗搴撳悕绉?': 'Material Library Name',
  '璇疯緭鍏ョ礌鏉愬簱鍚嶇О': 'Please enter material library name',
  '绱犳潗搴撴暟閲?': 'Material Libraries',
  '褰撳墠瑙嗛鏁?': 'Current Videos',
  '绱犳潗瑙嗛': 'Material Videos',
  '鍒嗙被': 'Category',
  '璇疯緭鍏ュ垎绫?': 'Please enter category',
  '鍦烘櫙': 'Scene',
  '瑙嗛鏁?': 'Videos',
  '瑙嗛': 'Video',
  '瀹归噺': 'Size',
  '鏍煎紡': 'Format',
  '鏍囩': 'Tags',
  '鏂板缓绱犳潗搴?': 'New Library',
  '涓婁紶瑙嗛': 'Upload Videos',
  '涓婁紶': 'Upload',
  '绛涢€?': 'Filter',
  '鍏ㄩ儴鐢ㄩ€?': 'All Uses',
  '鏀逛负': 'Change to',
  '淇敼宸查€夌敤閫?': 'Change Selected Use',
  '涓婁紶鍒板綋鍓嶇礌鏉愬簱': 'Upload to Current Library',
  '鍏抽敭鐢ㄩ€旂己灏?': 'Missing key uses',
  '灏侀潰': 'Cover',
  '鏂囦欢鍚?': 'File Name',
  '绱犳潗搴揑D': 'Library ID',
  '鏃堕暱': 'Duration',
  '鍒嗚鲸鐜?': 'Resolution',
  '澶у皬': 'Size',
  '鐢ㄩ€?': 'Use',
  '澶辫触鍘熷洜': 'Failure Reason',
  '閫氱敤绱犳潗': 'General Material',
  '閫氱敤': 'General',
  '榛勯噾3绉?': 'Golden 3 Seconds',
  '鐥涚偣鍦烘櫙': 'Pain-point Scene',
  '浜у搧浜浉': 'Product Reveal',
  '浣跨敤婕旂ず': 'Usage Demo',
  '鏁堟灉璇佹槑': 'Result Proof',
  '缁嗚妭鐗瑰啓': 'Detail Close-up',
  '鍦烘櫙铻嶅叆': 'Lifestyle Scene',
  'S1 榛勯噾3绉?': 'S1 Golden 3 Seconds',
  'S2 鐥涚偣鍦烘櫙': 'S2 Pain-point Scene',
  'S3 浜у搧浜浉': 'S3 Product Reveal',
  'S4 浣跨敤婕旂ず': 'S4 Usage Demo',
  'S5 鏁堟灉璇佹槑': 'S5 Result Proof',
  'S6 缁嗚妭鐗瑰啓': 'S6 Detail Close-up',
  'S7 鍦烘櫙铻嶅叆': 'S7 Lifestyle Scene',

  // Generation and publishing.
  '鐢熸垚浠诲姟': 'Generation Task',
  'AI鏂囨': 'AI Script',
  '閰嶉煶': 'Voiceover',
  '褰撳墠姝ラ': 'Current Step',
  '鍓緫缁撴瀯': 'Clip Structure',
  '鐢熸垚鐘舵€?': 'Generation Status',
  '杈撳嚭鏂囦欢': 'Output File',
  '鐢熸垚璇︽儏': 'Generation Details',
  '鐢熸垚缁撴灉': 'Generation Result',
  '鍙戝竷浠诲姟': 'Publishing Tasks',
  '鍙戝竷鏄庣粏': 'Publishing Details',
  '寰呭彂甯冭棰?': 'Videos to Publish',
  '璐﹀彿鐭╅樀': 'Account Matrix',
  '瀹樻柟鎺堟潈': 'Official Authorization',
  '浜岀淮鐮佹巿鏉?': 'QR Code Authorization',
  '浠诲姟鏍囬': 'Task Title',
  '鍙戝竷': 'Publish',
  '鍙戝竷鍒?': 'Publish to',
  '鍙戝竷鏍囬': 'Publish Title',
  '鍙戝竷鏂囨': 'Publish Caption',
  '鍙戝竷璐﹀彿': 'Publishing Account',
  '璐﹀彿鍒嗙粍': 'Account Groups',
  '鍙戝竷妯″紡': 'Publish Mode',
  '闅愮': 'Privacy',
  '浜掑姩': 'Interactions',
  '鍐呭鏍囪瘑': 'Content Disclosure',
  '鍏佽璇勮': 'Allow Comments',
  '鍏佽鍚堟媿': 'Allow Duet',
  '鍏佽鎷兼帴': 'Allow Stitch',
  '璇勮': 'Comments',
  '鍚堟媿': 'Duet',
  '鎷兼帴': 'Stitch',
  '鍟嗕笟鍐呭': 'Commercial Content',
  '鍝佺墝鍐呭': 'Branded Content',
  '寮€濮嬪彂甯?': 'Start Publishing',
  '浠呰嚜宸卞彲瑙?': 'Only Me',
  '濂藉弸鍙': 'Friends',
  '绮変笣鍙': 'Followers',
  '鍏紑': 'Public',
  '榛樿浣跨敤璐﹀彿閰嶇疆': 'Use account defaults',
  '浜岀淮鐮佹湭鐢熸垚': 'QR code not generated',
  '鍒锋柊鐘舵€?': 'Refresh Status',
  '璐﹀彿鍙戝竷閰嶇疆': 'Account Publish Settings',
  '榛樿闅愮': 'Default Privacy',
  '榛樿浜掑姩': 'Default Interactions',
  '榛樿寮€鍏?': 'Default Switches',
  '鍒嗙粍': 'Group',
  '璐﹀彿鏁?': 'Accounts',
  '澶囨敞': 'Remarks',
  '妯″紡': 'Mode',
  '鏈湴鐘舵€?': 'Local Status',
  'TikTok鐘舵€?': 'TikTok Status',
  '鍚屾鏃堕棿': 'Sync Time',
  '閲嶈瘯娆℃暟': 'Retries',
  '鏍囬': 'Title',
  '鏂囨': 'Script',
  '鍚嶇О': 'Name',
  '鐢ㄦ埛鍚?': 'Username',
  '璐﹀彿': 'Account',
  '鎺堟潈': 'Authorization',
  '鏈夋晥': 'Valid',
  '寮傚父': 'Invalid',
  '杩囨湡': 'Expired',
  '鏈缃満鏅?': 'Scene not set',

  // Voice and creative pages.
  '鎴戠殑闊宠壊': 'My Voice',
  '杈撳叆闊宠壊鍚嶇О': 'Enter voice name',
  '閫夋嫨闊抽': 'Choose Audio',
  '鍒涘缓闊宠壊': 'Create Voice',
  '鎴戝凡鑾峰緱璇磋瘽浜烘垨鏉冨埄浜虹殑鏄庣‘鎺堟潈': 'I have obtained explicit authorization from the speaker or rights holder',
  '鏀寔': 'Supports',
  '鏆傛棤鑷畾涔夐煶鑹?': 'No custom voices',
  '璇曞惉': 'Preview',
  '澶嶅埢涓?': 'Cloning',
  '鍙娇鐢?': 'Ready',
  '宸插仠鐢?': 'Disabled',
  '鐢熸垚鍒涙剰': 'Generate Creative',
  '鐢熸垚涓?': 'Generating',
  '鎻愮ず璇嶅姪鎵?': 'Prompt Assistant',
  '鎺ㄨ崘': 'Recommended',
  '鍏ㄩ儴': 'All'
}

const sortedPhrases = Object.keys(phraseMap).sort((a, b) => b.length - a.length)

export const containsCjk = (text?: string) => Boolean(text && cjkPattern.test(text))

export const sanitizeEnglishVisibleText = (text?: string) => {
  if (!text) {
    return ''
  }
  if (phraseMap[text]) {
    return phraseMap[text]
  }
  let sanitized = text
  sortedPhrases.forEach((phrase) => {
    if (sanitized.includes(phrase)) {
      sanitized = sanitized.split(phrase).join(phraseMap[phrase])
    }
  })
  if (!containsCjk(sanitized)) {
    return sanitized
  }
  return text
}

export const sanitizeEnglishAttributeText = (text?: string) => sanitizeEnglishVisibleText(text)

export const sanitizeEnglishTitleText = (text?: string) => sanitizeEnglishVisibleText(text)
